In [1]:
import pandas as pd

produits.csv scrapé

In [17]:
df = pd.read_csv("../../RGBD/table_produits/produits.csv")
df.head(1)

,url,nom_produit,img_produit,prix_produit,contenance,pg_vg,origine,frais,surbooste,saveur,description,brand,gout,info_brand,id_produit
0,https://www.aromes-et-liquides.fr/e-liquide-ul...,Ragnarok Ultimate A&L,https://assets.aromes-et-liquides.fr/53645-thi...,5.9,10ml,50/50,France,Oui,Non,"cassis, lime, fruits rouges, parfait",Le e-liquide Ragnarok par A&L Ultimate est un ...,Arômes et Liquides (A&L),fruit,Arômes et Liquides (A&L) est un fabricant fran...,1

In [18]:
df.columns

Index(['url', 'nom_produit', 'img_produit', 'prix_produit', 'contenance',
       'pg_vg', 'origine', 'frais', 'surbooste', 'saveur', 'description',
       'brand', 'gout', 'info_brand', 'id_produit'],
      dtype='object')

 des valeurs manquantes

In [19]:
df.isna().sum()

url             0
nom_produit     0
img_produit     0
prix_produit    6
contenance      0
pg_vg           0
origine         0
frais           0
surbooste       0
saveur          0
description     0
brand           0
gout            0
info_brand      0
id_produit      0
dtype: int64

In [20]:
df['prix_produit'].isnull().sum()

6

In [16]:
df.columns

Index(['index', 'url', 'nom_produit', 'img_produit', 'prix_produit',
       'contenance', 'pg_vg', 'origine', 'frais', 'surbooste', 'saveur',
       'description', 'brand', 'gout', 'info_brand', 'id_produit'],
      dtype='object')

In [6]:
df.reset_index(inplace=True)
df.tail(1)

,index,url,nom_produit,img_produit,prix_produit,contenance,pg_vg,origine,frais,surbooste,saveur,description,brand,gout,info_brand,id_produit
1530,1530,https://www.aromes-et-liquides.fr/e-liquide-al...,Blond Sec Sel de Nicotine Pur Distillat Alfali...,https://assets.aromes-et-liquides.fr/55762-thi...,5.9,10ml,50/50,France,Non,Non,"anis, lime, tabac",Voici la recette du Blond Sec de chez Alfaliqu...,Alfaliquid,classique,Le fabricant français s'est fait reconnaître p...,1533

Limitation de la taille des entrées pour les modèles d'Azure OpenAI

In [7]:
df = df.iloc[:100]
df.to_csv('rag_csv.csv', index=False)